stages:
  - search
  - fetch-configmap
  - fetch-sts
  - consolidate-output

variables:
  INSTANCE_NAME: "virtualmeetingmgmt"  # Replace with the partial instance name
  STS_NAME: "virtualmgmt-test-redis-ha-server"  # Replace with actual StatefulSet name
  NAMESPACE: "cache-test"
  KUBECTL: "bitnami/kubectl:latest"
  CENTOS: "centos:7"

# Step 1: Search for all pods that match the partial instance name
search_pods:
  image: $KUBECTL
  stage: search
  script:
    - |
      echo "Searching for pods matching $INSTANCE_NAME in $NAMESPACE namespace"
      kubectl get pods -n $NAMESPACE | grep $INSTANCE_NAME > found_pods.txt
      if [[ -s found_pods.txt ]]; then
        echo "Pods matching $INSTANCE_NAME found:"
        cat found_pods.txt
      else
        echo "No pods matching $INSTANCE_NAME found"
      fi
  tags:
    - cache-utility-test
  artifacts:
    paths:
      - found_pods.txt
    when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE != "push" && $CI_PIPELINE_SOURCE != "merge_request_event"'

# Step 2: Fetch the ConfigMap and extract the redis.conf section
fetch_configmap:
  image: $KUBECTL
  stage: fetch-configmap
  needs:
    - search_pods
  script:
    - |
      echo "Fetching ConfigMap for $INSTANCE_NAME"
      CONFIGMAP_NAME=$(kubectl get configmaps -n $NAMESPACE | grep "$INSTANCE_NAME-redis-ha-configmap" | awk '{print $1}')
      
      if [[ ! -z "$CONFIGMAP_NAME" ]]; then
        echo "Found ConfigMap: $CONFIGMAP_NAME"
        # Fetch the entire ConfigMap and extract the redis.conf section until 'logfile'
        kubectl get configmap $CONFIGMAP_NAME -n $NAMESPACE -o yaml > full_configmap_output.yaml
        cat full_configmap_output.yaml | sed -n '/redis\.conf: |/,/logfile/p' > redis_conf_output.txt
      else
        echo "No ConfigMap found for $INSTANCE_NAME"
      fi
  tags:
    - cache-utility-test
  artifacts:
    paths:
      - redis_conf_output.txt
    when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE != "push" && $CI_PIPELINE_SOURCE != "merge_request_event"'

# Step 3: Fetch StatefulSet (STS) details, parse container information, and extract resource limits
fetch_sts:
  image: $KUBECTL
  stage: fetch-sts
  needs:
    - fetch_configmap
  script:
    - |
      echo "Fetching StatefulSet details for $STS_NAME"
      kubectl get sts $STS_NAME -n $NAMESPACE -o json > sts_output.json

      # Parsing the container details using jq
      echo "Parsing the StatefulSet container details"
      jq '.spec.template.spec.containers[] | {name: .name, image: .image, resources: .resources}' sts_output.json > parsed_sts_output.json
  tags:
    - cache-utility-test
  artifacts:
    paths:
      - parsed_sts_output.json
    when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE != "push" && $CI_PIPELINE_SOURCE != "merge_request_event"'

# Step 4: Consolidate the output and print the results
consolidate_output:
  image: $CENTOS
  stage: consolidate-output
  needs:
    - fetch_sts
  script:
    - |
      echo "Consolidating the output"
      echo "Pods and ConfigMap information for $INSTANCE_NAME:" > final_report.txt
      if [[ -s found_pods.txt ]]; then
        cat found_pods.txt >> final_report.txt
      else
        echo "No matching pods found" >> final_report.txt
      fi

      echo "---- Redis Config (redis.conf) ----" >> final_report.txt
      cat redis_conf_output.txt >> final_report.txt

      echo "---- StatefulSet (STS) Container Details ----" >> final_report.txt
      cat parsed_sts_output.json >> final_report.txt
  tags:
    - general-runner
  artifacts:
    paths:
      - final_report.txt
    when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE != "push" && $CI_PIPELINE_SOURCE != "merge_request_event"'
